name: Deploy static site

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload static files
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: .  # Or ./dist, ./build, etc. depending on your site structure

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
