name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deploy on changes to the main branch

permissions:
  contents: read  # Needed to read the contents of the repository
  pages: write    # Needed to write the Pages deployment
  id-token: write # For accessing the necessary tokens

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Upload the files for GitHub Pages
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./  # Make sure this points to the correct folder (e.g., ./dist/ or ./)

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          artifact_name: github-pages  # Reference the uploaded artifact by its name
          publish_dir: ./  # Make sure this points to the correct folder (e.g., ./dist/ or ./)