name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger deploy on changes to the main branch

permissions:
  contents: read  # Needed to read the contents of the repository
  pages: write    # Needed to write the Pages deployment
  id-token: write # For accessing the necessary tokens

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # (Optional) Set up any environment (if you need npm, etc.)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # (Optional) Install dependencies (if you have npm packages)
      - name: Install dependencies 
        run: |
          npm install  # or any relevant install command

      # Upload the files for GitHub Pages
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./  # Make sure this points to the correct folder (e.g., ./dist/ or ./)

      # Deploy to GitHub Pages using the artifact
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        with:
          branch: main  # Or the branch you're deploying from
          folder: ./   # Make sure this folder is correct (e.g., `./` or `./dist`)
